# LAB | Intro to Machine Learning

**Load the data**

In this challenge, we will be working with Spaceship Titanic data. The data can be found here:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv

Metadata

https://github.com/data-bootcamp-v4/data/blob/main/spaceship_titanic.md

In [18]:
#import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [19]:
spaceship = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv")
spaceship.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

**Check the shape of your data**

In [24]:
#your code here
spaceship.shape

(6606, 14)

**Check for data types**

In [6]:
#your code here
spaceship.dtypes

PassengerId      object
HomePlanet       object
CryoSleep        object
Cabin            object
Destination      object
Age             float64
VIP              object
RoomService     float64
FoodCourt       float64
ShoppingMall    float64
Spa             float64
VRDeck          float64
Name             object
Transported        bool
dtype: object

**Check for missing values**

In [16]:
#your code here
spaceship.isna().sum()

PassengerId     0
HomePlanet      0
CryoSleep       0
Cabin           0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Name            0
Transported     0
dtype: int64

There are multiple strategies to handle missing data

- Removing all rows or all columns containing missing data.
- Filling all missing values with a value (mean in continouos or mode in categorical for example).
- Filling all missing values with an algorithm.

For this exercise, because we have such low amount of null values, we will drop rows containing any missing value.

In [25]:
#your code here
spaceship.dropna(inplace = True)
spaceship.isnull().sum()
spaceship.shape

(6606, 14)

**KNN**

K Nearest Neighbors is a distance based algorithm, and requeries all **input data to be numerical.**

Let's only select numerical columns as our features.

In [30]:
#your code here
spaceship_num = spaceship.select_dtypes('number')
spaceship_num.head()

    Age  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck
0  39.0          0.0        0.0           0.0     0.0     0.0
1  24.0        109.0        9.0          25.0   549.0    44.0
2  58.0         43.0     3576.0           0.0  6715.0    49.0
3  33.0          0.0     1283.0         371.0  3329.0   193.0
4  16.0        303.0       70.0         151.0   565.0     2.0

And also lets define our target.

In [37]:
#your code here
from sklearn.model_selection import train_test_split
target = spaceship_num.VRDeck
features = spaceship_num.loc[:, ~ spaceship_num.columns.isin(['VRDeck'])]

features.head()

    Age  RoomService  FoodCourt  ShoppingMall     Spa
0  39.0          0.0        0.0           0.0     0.0
1  24.0        109.0        9.0          25.0   549.0
2  58.0         43.0     3576.0           0.0  6715.0
3  33.0          0.0     1283.0         371.0  3329.0
4  16.0        303.0       70.0         151.0   565.0

**Train Test Split**

Now that we have split the data into **features** and **target** variables and imported the **train_test_split** function, split X and y into X_train, X_test, y_train, and y_test. 80% of the data should be in the training set and 20% in the test set.

In [40]:
#your code here
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size = 0.2,  random_state = 12)

X_train.head()

       Age  RoomService  FoodCourt  ShoppingMall     Spa
7880  19.0          0.0        0.0           0.0     0.0
2415  18.0       1102.0        9.0        2628.0     0.0
1594  28.0          0.0       26.0          88.0     5.0
6608  28.0          0.0      160.0           0.0  1538.0
8058  13.0          0.0        0.0           0.0     0.0

**Model Selection**

In this exercise we will be using **KNN** as our predictive model.

You need to choose between **Classificator** or **Regressor**. Take into consideration target variable to decide.

Initialize a KNN instance without setting any hyperparameter.

In [57]:
#your code here
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor(n_neighbors=100)

Fit the model to your data.

In [58]:
#your code here
knn.fit(X_train, y_train)
prediction = knn.predict(X_test)

Evaluate your model.

In [59]:
#your code here
print(f"The accuracy of the model is {knn.score(X_test, y_test): .2f}%")

The accuracy of the model is  0.16%

**Congratulations, you have just developed your first Machine Learning model!**